--- 
abstract: turn templates into static websites
author: 
  - Chisel Wright<chiselwright@users.berlios.de>
build_requires: 
  Test::More: 0.72
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Zucchini
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Config::General: 2.37
requires: 
  Carp: 0
  Class::Std: 0.0.8
  Config::Any: 0.08
  Digest::MD5: 2.36
  File::Copy: 2.09
  File::Rsync: 0.42
  File::stat: 1.00
  IO::File: 0
  Template: 2.19
version: 0.0.1
